### ISSUE TITLE
viewer_error

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/landsat-tiler#12]
The viewer is hitting an error. I am not sure why. Example screenshot below. I'm going to play around with trying to make a simplified version of this viewer to 1) understand a bit better what it is doing and 2) hopefully isolate the problem.

(the Sentinel 2 viewer might also be hitting the same issue.. which perhaps indicates that I have got an issue on my end, will test and report).

![unknown_error](https://user-images.githubusercontent.com/16657983/36484948-bd93a118-1712-11e8-9cbc-20093260fa18.png)

**Comment by vincentsarago** [comment]
thanks @samsammurphy I'm going to check this. 
In the same time FYI, I've build a bundle of Landsat, Sentinel and CBERS tiler in https://github.com/RemotePixel/remotepixel-tiler you may want to checkout that.

**Comment by vincentsarago** [comment]
@samsammurphy strange I couldn't reproduce the error. 
To me it seems that API gateway is not sending proper PNG/JPEG to mapbox gl. 
Can you check the specific response (+header) for a tile request ?

**Comment by samsammurphy** [comment]
@vincentsarago The remotepixel-tiler is a thing of beauty.

The error was on my end. I was using the wrong `landsat_tiler_url`, apologies. Everything is working.
