### ISSUE TITLE
Mapbox style not found

### ISSUE THREAD

**Issue by fredliporace** [mapbox/landsat-tiler#6]
Hello,

Thanks for the great tool.

I successfully deployed the app but while using viewer/js/app.js I got an error while trying to download a mapbox style:

 https://api.mapbox.com/styles/v1/vincentsarago/ciy1m6t8y005a2rr09jhfplg3?access_token=***MY_MAPBOX_TOKEN***

The error is
 {message: "Style not found"}

Could that be a token issue?

**Comment by vincentsarago** [comment]
dear @fredliporace sorry about that, the style was in private mode :-(

Should be fixed now 🎉
