### ISSUE TITLE
landsat-tiler deploy requires region

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/landsat-tiler#9]
Following the [README.md](https://github.com/mapbox/landsat-tiler#deploy-to-aws) hit an error on `sls deploy`; i.e. lambda role does not exist
![nolambdarole](https://user-images.githubusercontent.com/16657983/36310462-022a88ba-1320-11e8-9ad5-030e0b0d2cac.png)

Specifying the region as a command line argument fixed the issue:

`sls deploy --region us-west-2`.

This is odd as the region was set in the serverless.yml
![region_in_yml](https://user-images.githubusercontent.com/16657983/36310660-ac1b1ef2-1320-11e8-9c5c-174e33d87c46.png)

I suspect that this might be an issue with serverless in general (as opposed to something specific to landsat-tiler). However, I am not sure though, so was hoping for your advice @vincentsarago.

If this is a serverless issue then 1) I intend to post the issue [here](https://github.com/serverless/serverless), 2) It might be a good idea / nice to update the landsat-tiler README with the command line work around. What do you reckon?

**Comment by vincentsarago** [comment]
👋 well this is strange! 

can you try `AWS_REGION=us-west-2 sls deploy` ? (not sure why but maybe it's not working if you don't have any default region set in your env)

**Comment by samsammurphy** [comment]
:wave: Happy to.. (deploying).. That worked! 🎉 

This is what my configuration file looked like
```
$ cat ~/.aws/config
# [profile sam-admin]
# region = eu-west-2
# [default]
# region = eu-west-2
```

When I defined the region at the command line I was hitting a CORS error (below), which makes me suspect that there might be multiple regions somehow being used, but the AWS_REGION variable fixed that too! =D
![cors_error](https://user-images.githubusercontent.com/16657983/36313586-e182bd62-1329-11e8-82ad-6dc66cc2534e.png)

**Comment by samsammurphy** [comment]
Closing because it seems this is not a landsat-tiler issue.
